### PR TITLE
Finalize Salvo's migration to AZP.

### PR DESCRIPTION
**Pull request by mum4k**
- Add multiple stages and define dependencies. The CI will no longer attempt to test if the code doesn't build or to run coverage if the tests are failing.
- Decreasing timeout for each stage to 120 minutes.
- Execute build and format in parallel.
- Deleting references to circleci.
- Moving repokitteh commands to AZP.

Signed-off-by: Jakub Sobon <mumak@google.com>

### CODE REVIEW

**Review by fei-deng — APPROVED** [review]
LGTM

**Review by gyohuangxin — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
