### PR TITLE
Update Envoy & enable coverage test in CI

### PR DESCRIPTION
**Pull request by oschaaf**
Signed-off-by: Otto van der Schaaf <oschaaf@we-amp.com>

### CODE REVIEW

**Comment by oschaaf** [comment]
The coverage logs shows a pattern of segmentation faults:

```
bazel-out/k8-fastbuild/bin/nighthawk/test/_objs/nighthawk_test_lib/platform_util_test.pic.gcda
external/bazel_tools/tools/test/collect_cc_coverage.sh: line 113:  1055 Segmentation fault      "${GCOV}" -i -b -o "$(dirname ${gcda})" "${gcda}" &> "$gcov_log"
```

**Comment by oschaaf** [comment]
With the segmentation faults gone, coverage is still failing. But this looks like progress. Now the bazel coverage log ends with:

```
Reading data file bazel-out/_coverage/_coverage_report.dat
Resolved relative source file path "bison_parser.y" with CWD to "/root/project/bison_parser.y".
Found 29 entries.
Found common filename prefix "/root/project/nighthawk"
Writing .css and .png files.
Generating output.
Processing file /root/project/bison_parser.y
genhtml: ERROR: cannot read /root/project/bison_parser.y
Exited with code 2
```

**Comment by htuch** [comment]
@oschaaf it looks like the Bison code, which is probably coming via the Envoy submodule, is being included within the instrumentation filter, as we're getting a `.gcov` output. Can we either move Envoy submodule out of this path, make the filter more specific or switch to using Bazel `git_repository` instead of submodule?

**Comment by oschaaf** [comment]
Cool, it's working! The html report is there as well, satisfying the 97.5% requirement shouldn't be hard.
Let me tidy this PR up for a bit.

```
Overall coverage rate:
  lines......: 93.0% (346 of 372 lines)
  functions..: 89.4% (118 of 132 functions)
HTML coverage report is in /root/project/generated/coverage/coverage.html
Code coverage 93.0 is lower than limit of 97.5
Exited with code 1
```

**Comment by oschaaf** [comment]
@htuch thanks; coverage is hooked up and working. Added two tests to get passing with the 97.5% target.

**Pull request merged**
