### PR TITLE
Syncing configuration files from Nighthawk and Envoy (09/14/2022)

### PR DESCRIPTION
**Pull request by gyohuangxin**
Signed-off-by: Huang Xin <xin1.huang@intel.com>

### CODE REVIEW

**Comment by gyohuangxin** [comment]
@mum4k I think we can add `retest` hook

**Comment by gyohuangxin** [comment]
@mum4k Now the tests are OK.

**Comment by mum4k** [comment]
@gyohuangxin agreed, once we finish the migration to AZP and deprecate CircleCI completely, we can add retest on AZP. I can look into this in October.

**Review by mum4k — APPROVED** [review]

**Pull request merged**
