### PR TITLE
Syncing configuration files from Nighthawk and Envoy (03/14/2023)

### PR DESCRIPTION
**Pull request by gyohuangxin**

### CODE REVIEW

**Comment by gyohuangxin** [comment]
Investigating the failure...

**Comment by phlax** [comment]
hi @gyohuangxin i see the docker-related CI is failing, ive made quite a few changes to this recently

im wondering if you are using docker inside the build container ?

there are some other possibilities i can think of also, lmk if i can help

**Comment by gyohuangxin** [comment]
@phlax Thanks for your help. Yes, I think so. I can run the same test on my own machine, but it failed in the AZP pipeline.

**Comment by phlax** [comment]
@gyohuangxin trying to understand relationship with nighthawk - but see https://github.com/envoyproxy/nighthawk/pull/977 for related fix

**Comment by gyohuangxin** [comment]
@phlax The CI pipeline of envoy-perf is similar with nighthawk, I will try it.

**Comment by phlax** [comment]
just flagging that the reason it is now disabled by default is that it breaks the security model of running inside a container - anything running with the default user inside the container can trivially get root on the host

**Review by mum4k — APPROVED** [review]
Thank you both. I am going to rework the CI pipeline here according to [this design](https://docs.google.com/document/d/1auXzV-AEXgMzbtdG06XlZ2d9X5l_XadMheA9h51E7yc/edit#bookmark=id.k5jg61c9551x), so this will go away shortly.

**Pull request merged**
