### PR TITLE
add pip deps for salvo_install_deps_install

### PR DESCRIPTION
**Pull request by xu1zhou**
add pip deps for salvo_install_deps_install.sh

### CODE REVIEW

**Comment by gyohuangxin** [comment]
@xu1zhou Thanks for adding this dependencies. I think it's helpful. Can you sign your commit?

**Comment by mum4k** [comment]
@xu1zhou thank you for the contribution. As @gyohuangxin indicated, we require commits to be signed.

You can follow this guide that explains how to sign commits:

https://github.com/envoyproxy/envoy-perf/pull/148/checks?check_run_id=6850203762

**Comment by xu1zhou** [comment]
Thanks for your suggestion @gyohuangxin  @mum4k , have added sigh-off.

**Review by gyohuangxin — APPROVED** [review]
LGTM

**Review by mum4k — APPROVED** [review]

**Pull request merged**
